/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TimeBank } from "./TimeBank";
export { TimeBank__factory } from "./factories/TimeBank__factory";
